# Java 21
FROM gitlab-registry.insee.fr:443/kubernetes/images/run/jre:21.0.1_12-jre-jammy-rootless
COPY --chown=$JAVA_USER:$JAVA_USER target/kraftwerk-api-*.jar kraftwerk.jar

ENTRYPOINT ["java","-jar","/kraftwerk.jar"]