Feature: Do we apply a VTL instruction correctly?
  Everybody wants to know if we apply a single VTL instruction

  Scenario Outline: Do we apply the VTL instructions ?
    Given We have some simple VTLBindings
    When I try to apply some VTL instruction : "<vtlScript>"
    Then The binding "<outputDataset>" should have <numberVariables> variables
    
    Examples:
    # We apply some script and we check if the final output got this change
    # Parameters : 
    # - vtlScript : script in VTL to apply
    # - outputDataset : name of the final table generated by all the scripts
    # - numberVariables : expected number of variables in the final table, based on the vtl changes that's expectedly applied
    | vtlScript                                        | outputDataset| numberVariables |
    | OUTPUT := COLEMAN [keep interrogationId, LAST_NAME];        | OUTPUT       | 2               |
    | OUTPUT := COLEMAN [keep LAST_NAME];              | OUTPUT       | 1               |
    | OUTPUT := COLEMAN [calc newinterrogationId := interrogationId];        | OUTPUT       | 17              |
    | OUTPUT := COLEMAN [rename LAST_NAME to Label_1B];| OUTPUT       | 16              |
    | COLEMAN := COLEMAN [drop LAST_NAME];             | COLEMAN      | 15              |
    